### PR TITLE
Fix label background in SharedInput

### LINKED ISSUE #2909: Gas limit input label overlaps with the input border
### Discord Discussion Link

_No response_

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Change gas settings

### What did not work?

The label for gas limit overlaps the input border

image

### Version

v0.19.0

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dmtrbrl**
Before:
image

After:
image

Fixes #2909

Latest build: [extension-builds-2918](https://github.com/tallyhowallet/extension/suites/10585916210/artifacts/527334315) (as of Wed, 25 Jan 2023 21:52:22 GMT).

### CODE REVIEW

**Review by jagodarybacka — COMMENTED** [review]
Looks good but please sign your commit as it is showing here as not verified 😉

**Comment by dmtrbrl** [comment]
@jagodarybacka done 🙃
It was signed, but for some reason after triggering an update with main branch via Github UI it cleared the signature 🤦‍♂️

**Review by hyphenized — CHANGES_REQUESTED** [review]
Thanks a lot @dmtrbrl! This breaks styles in inputs that do not have backgrounds, could you revise this please?

Before: 

image

After: 

image

**Comment by hyphenized** [comment]
> Hi @hyphenized How can I access the screen you mentioned? I see a bit different screen in onboarding. It has a darker background, a bit different text and the new styling fits well.

My bad, this screen is part of an onboarding revamp. To access it add `SUPPORT_TABBED_ONBOARDING=true` to your `.env` file and rebuild/restart the development server.

**Comment by dmtrbrl** [comment]
Fixed

**Review by hyphenized — APPROVED** [review]
Sweet, this is great. Thanks!

**Pull request merged**
