### PR TITLE
Proposal: Autofocus on input when editing account name

### PR DESCRIPTION
**Pull request by dmtrbrl**
From the UX perspective this behaviour is much better.

Before:
before

After:
after

Latest build: [extension-builds-2824](https://github.com/tallyhowallet/extension/suites/10112232727/artifacts/494898183) (as of Mon, 02 Jan 2023 03:37:26 GMT).

### CODE REVIEW

**Review by mhluongo — DISMISSED** [review]
Concept ACK! No opinions on the implementation's code, so one more +1 for merge would be nice

**Review by jagodarybacka — APPROVED** [review]
Works nice! ✨ 
Please[ sign your commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) so we can merge it

**Comment by dmtrbrl** [comment]
@jagodarybacka done

**Review by mhluongo — APPROVED** [review]
Happy with @jagodarybacka 's sign-off, let's do it!

**Pull request merged**
